# Generated by Django 2.2.6 on 2020-01-08 16:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(default='desc', max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=2000)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('see_hikes', models.CharField(choices=[('noone', 'noone'), ('friends', 'friends'), ('all', 'all')], default='all', max_length=10)),
                ('add_to_participation', models.CharField(choices=[('noone', 'noone'), ('friends', 'friends'), ('all', 'all')], default='noone', max_length=10)),
                ('request_for_participation', models.CharField(choices=[('noone', 'noone'), ('friends', 'friends'), ('all', 'all')], default='all', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A new hike', max_length=200)),
                ('description', models.CharField(default='', max_length=200000)),
                ('short_description', models.CharField(default='', max_length=1000)),
                ('start_date', models.DateField(default='2020-01-02')),
                ('end_date', models.DateField(default='2020-01-02')),
                ('difficulty', models.CharField(default='none', max_length=200)),
                ('type_of_hike', models.CharField(default='Пеший', max_length=200)),
                ('coordinates', models.CharField(default='[]', max_length=200000)),
                ('creation_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 8, 18, 10, 51, 162441))),
                ('image', models.ImageField(blank=True, null=True, upload_to='hikes/')),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('landmarks', models.ManyToManyField(blank=True, to='ChatApp.Landmark')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
