# Generated by Django 2.2.6 on 2020-01-18 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0016_auto_20200118_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 18, 59, 46, 140845)),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
