# Generated by Django 2.2.6 on 2020-01-18 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0017_auto_20200118_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 0, 26, 9, 843002)),
        ),
    ]
