# Generated by Django 3.0.2 on 2020-01-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0018_auto_20200119_0026'),
        ('FreeFallApp', '0018_auto_20200119_2054'),
    ]

    operations = [
    ]
