# Generated by Django 3.0.2 on 2020-01-21 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0019_merge_20200121_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 21, 9, 34, 23, 720170)),
        ),
    ]
