# Generated by Django 2.2.7 on 2020-01-21 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0020_auto_20200121_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 21, 18, 33, 11, 119131)),
        ),
    ]
