# Generated by Django 3.0.2 on 2020-02-04 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0024_auto_20200204_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default='2020-01-02'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 11, 5, 6, 237478)),
        ),
    ]
