# Generated by Django 2.2.6 on 2020-02-04 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0026_auto_20200204_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='days',
        ),
        migrations.AlterField(
            model_name='day',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='day',
            name='description',
            field=models.CharField(default='', max_length=200000),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 17, 12, 51, 165921)),
        ),
    ]
