# Generated by Django 2.2.6 on 2020-02-04 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0027_auto_20200204_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='hike',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='FreeFallApp.Hike'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 17, 13, 32, 221166)),
        ),
    ]
