# Generated by Django 2.2.6 on 2020-02-05 19:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FreeFallApp', '0029_auto_20200204_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 21, 17, 10, 387294)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('request_for_ptc', 'request_for_ptc'), ('invite_to_hike', 'invite_to_hike'), ('user_added_to_hike', 'user_added_to_hike'), ('simple_text', 'simple_text')], default='simple_text', max_length=15)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('hike', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='FreeFallApp.Hike')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
