# Generated by Django 2.2.6 on 2020-02-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0034_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='join_to_group',
            field=models.CharField(choices=[('open', 'open'), ('request', 'request'), ('close', 'close')], default='request', max_length=10),
        ),
        migrations.AddField(
            model_name='hike',
            name='limit_of_members',
            field=models.IntegerField(blank=True, default=15, max_length=2000),
        ),
    ]
