# Generated by Django 3.0.2 on 2020-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0037_auto_20200210_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
