# Generated by Django 3.0.2 on 2020-02-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0038_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='hike',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='FreeFallApp.Hike'),
        ),
    ]
