# Generated by Django 3.0.2 on 2020-05-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0040_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
    ]
