# Generated by Django 3.0.2 on 2020-05-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0041_auto_20200512_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
