# Generated by Django 3.0.2 on 2020-05-24 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FreeFallApp', '0042_remove_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hike',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='FreeFallApp.Hike'),
        ),
    ]
