# Generated by Django 2.2.2 on 2019-11-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0008_hike_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='members',
            field=models.ManyToManyField(to='ChatApp.StandartUser'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='ChatApp.StandartUser'),
        ),
    ]
