# Generated by Django 2.2.6 on 2019-11-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standartuser',
            name='about_user',
        ),
        migrations.AddField(
            model_name='standartuser',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
    ]
