# Generated by Django 2.2.6 on 2020-01-18 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0014_auto_20200114_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landmarks/'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 13, 46, 27, 951307)),
        ),
    ]
