# Generated by Django 3.0.2 on 2020-01-19 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0017_auto_20200118_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 20, 54, 24, 550806)),
        ),
    ]
