# Generated by Django 2.2.6 on 2019-12-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0017_hike_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hike',
            name='landmarks',
            field=models.ManyToManyField(blank=True, to='ChatApp.Landmark'),
        ),
    ]
