# Generated by Django 2.2.7 on 2019-12-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0018_auto_20191209_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.CharField(default='', max_length=200000),
        ),
        migrations.AlterField(
            model_name='hike',
            name='short_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
