# Generated by Django 2.2.6 on 2019-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0019_auto_20191210_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='image',
        ),
        migrations.AddField(
            model_name='hike',
            name='436',
            field=models.ImageField(blank=True, null=True, upload_to='hikes/'),
        ),
    ]
