# Generated by Django 2.2.6 on 2019-12-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0020_auto_20191215_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='436',
            new_name='image',
        ),
    ]
