# Generated by Django 3.0.2 on 2020-01-28 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0021_auto_20200121_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 9, 47, 31, 756086)),
        ),
    ]
