# Generated by Django 3.0.2 on 2020-02-03 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0022_auto_20200128_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 17, 42, 59, 464547)),
        ),
    ]
