# Generated by Django 3.0 on 2019-12-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0022_auto_20191215_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hikes/'),
        ),
    ]
