# Generated by Django 3.0.2 on 2020-02-04 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0023_auto_20200203_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(default='Создатель слишком ленив, чтобы даже заполнить это поле.', max_length=200000)),
                ('coordinates', models.CharField(default='[]', max_length=200000)),
            ],
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 10, 46, 39, 574771)),
        ),
        migrations.AddField(
            model_name='hike',
            name='days',
            field=models.ManyToManyField(blank=True, to='ChatApp.Day'),
        ),
    ]
