# Generated by Django 2.2.6 on 2019-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0023_auto_20191217_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='creattion_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
