# Generated by Django 2.2.6 on 2019-12-27 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0024_hike_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 15, 25, 56, 308717)),
        ),
    ]
