# Generated by Django 2.2.6 on 2019-12-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0025_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='creattion_datetime',
            new_name='creation_datetime',
        ),
    ]
