# Generated by Django 2.2.6 on 2019-12-27 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0025_auto_20191227_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 15, 26, 30, 213242)),
        ),
    ]
