# Generated by Django 3.0.2 on 2020-02-04 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0025_auto_20200204_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='caption',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='day',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='days/'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 11, 42, 15, 961604)),
        ),
    ]
