# Generated by Django 2.2.6 on 2019-12-27 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0026_auto_20191227_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='coordinates',
            field=models.CharField(default='[]', max_length=200000),
        ),
        migrations.AlterField(
            model_name='hike',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 15, 30, 30, 113403)),
        ),
    ]
