# Generated by Django 2.2.7 on 2019-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0026_auto_20191224_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='coordinates',
            field=models.CharField(default='[]', max_length=200000),
        ),
    ]
