# Generated by Django 2.2.6 on 2020-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0035_auto_20200207_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='limit_of_members',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('request_for_ptc', 'request_for_ptc'), ('invite_to_hike', 'invite_to_hike'), ('user_added_to_hike', 'user_added_to_hike'), ('simple_text', 'simple_text')], default='simple_text', max_length=25),
        ),
    ]
