# Generated by Django 2.2.2 on 2019-11-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0004_auto_20191118_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='members',
        ),
    ]
