# Generated by Django 2.2.6 on 2019-11-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0005_remove_hike_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='categoory',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='hike',
            name='type_of_hike',
            field=models.CharField(default='Пеший', max_length=200),
        ),
    ]
