# Generated by Django 2.2.7 on 2019-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0007_auto_20191119_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='coordinates',
            field=models.CharField(default='', max_length=200000),
        ),
    ]
