# Generated by Django 2.2.2 on 2019-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0010_auto_20191120_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='short_description',
            field=models.CharField(default='desc', max_length=1000),
        ),
    ]
