# Generated by Django 2.2.6 on 2019-11-25 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0011_auto_20191125_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', limit_choices_to=200, null=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
