# Generated by Django 2.2.2 on 2019-11-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0015_auto_20191125_1901'),
        ('ChatApp', '0011_hike_short_description'),
    ]

    operations = [
    ]
